substitutions:
  name: "esp8266-evb-env"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: modwifi
  project:
    name: "olimex.esphome-${name}"
    version: "1.0"

dashboard_import:
  package_import_url: github://peter-valkov/test/${name}.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

wifi:
  reboot_timeout: 5min  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

# Enable captive portal
captive_portal:

i2c:
  sda: GPIO2
  scl: GPIO4

# sensors
sensor:
- platform: bme280
  temperature:
    name: "Temperature"
    oversampling: 16x
    id: TEMPERATURE
  pressure:
    name: "Pressure"
    id: PRESSURE
  humidity:
    name: "Humidity"
    id: HUMIDITY
  address: 0x76
  update_interval: 60s
  
- platform: ccs811
  eco2:
    name: "eCO2"
    id: ECO2
  tvoc:
    name: "Total Volatile Organic Compound"
    id: TVOC
  address: 0x5B
  update_interval: 60s

font:
  - file: fonts/DejaVuSans.ttf
    id: DejaVuSans_14
    size: 14
  - file: fonts/DejaVuSans.ttf
    id: DejaVuSans_20
    size: 20

image:
  - file: images/wifi-disconnected.png
    id: wifi_disconnected_img
  - file: images/thermometer.png
    id: thermometer_img
  - file: images/humidity.png
    id: humidity_img
  - file: images/pressure.png
    id: pressure_img
  - file: images/co2.png
    id: co2_img
  - file: images/tvoc.png
    id: tvoc_img

display:
  platform: ssd1306_i2c
  model: "SSD1306 128x64"
  rotation: 180
  id: OLED_DISPLAY
  on_page_change:
    to: PAGE_WIFI_DISCONNECTED
    then:
      if:
        condition:
          wifi.connected:
        then:
          display.page.show_next: OLED_DISPLAY
  pages:
    - id: PAGE_WIFI_DISCONNECTED
      lambda: |-
        it.image(32, 0, id(wifi_disconnected_img));
    - id: PAGE_TEMPERATURE
      lambda: |-
        it.image(0, 0, id(thermometer_img));
        it.printf(64, 0, id(DejaVuSans_14), TextAlign::TOP_CENTER, "Temperature");
        if (id(TEMPERATURE).has_state()) {
          it.printf(64, 16, id(DejaVuSans_20), TextAlign::TOP_CENTER, "%.1f°C", id(TEMPERATURE).state);
        }
    - id: PAGE_HUMIDITY
      lambda: |-
        it.image(0, 0, id(humidity_img));
        it.printf(64, 0, id(DejaVuSans_14), TextAlign::TOP_CENTER, "Humidity");
        if (id(HUMIDITY).has_state()) {
          it.printf(64, 16, id(DejaVuSans_20), TextAlign::TOP_CENTER, "%.1f%%", id(HUMIDITY).state);
        }
    - id: PAGE_PRESSURE
      lambda: |-
        it.image(0, 0, id(pressure_img));
        it.printf(64, 0, id(DejaVuSans_14), TextAlign::TOP_CENTER, "Pressure");
        if (id(PRESSURE).has_state()) {
          it.printf(64, 16, id(DejaVuSans_20), TextAlign::TOP_CENTER, "%.1f", id(PRESSURE).state);
          it.printf(64, 40, id(DejaVuSans_20), TextAlign::TOP_CENTER, "hPa");
        }
    - id: PAGE_ECO2
      lambda: |-
        it.image(0, 0, id(co2_img));
        it.printf(64, 0, id(DejaVuSans_14), TextAlign::TOP_CENTER, "CO2");
        if (id(ECO2).has_state()) {
          it.printf(64, 16, id(DejaVuSans_20), TextAlign::TOP_CENTER, "%.0f", id(ECO2).state);
          it.printf(64, 40, id(DejaVuSans_20), TextAlign::TOP_CENTER, "ppm");
        }
    - id: PAGE_TVOC
      lambda: |-
        it.image(0, 0, id(tvoc_img));
        it.printf(64, 0, id(DejaVuSans_14), TextAlign::TOP_CENTER, "TVOC");
        if (id(TVOC).has_state()) {
          it.printf(64, 16, id(DejaVuSans_20), TextAlign::TOP_CENTER, "%.0f", id(TVOC).state);
          it.printf(64, 40, id(DejaVuSans_20), TextAlign::TOP_CENTER, "ppb");
        }

interval:
  interval: 5s
  then:
    - display.page.show_next: OLED_DISPLAY
    - component.update: OLED_DISPLAY

