substitutions:
  name: "esp8266-evb-irda"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: modwifi
  project:
    name: "olimex.esphome-${name}"
    version: "1.0"

dashboard_import:
  package_import_url: github://peter-valkov/test/${name}.yaml

# Logging over UART1 (required) UART0 used for IR send/receive
logger:
  hardware_uart: UART1

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

wifi:
  reboot_timeout: 5min  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

# Enable captive portal
captive_portal:

# TODO - add themperature sensor

# Enable receiver
remote_receiver:
  id: receiver
  pin:
    number: GPIO3
    inverted: true
    mode:
      input: true
      pullup: true
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%
  dump: all

# Enable transmiter
remote_transmitter:
  id: transmitter
  pin: GPIO1
  carrier_duty_percent: 50%

climate:
  platform: fujitsu_general
  name: "Fujitsu General"
  # sensor: temperature_sensor_id
  transmitter_id: transmitter
  receiver_id: receiver
